### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by stefanos82** [codepotent/Head-Cleaner#2]
# Description 

Downloaded the zip version from here, activated it, it threw errors.

# Steps to Reproduce
1. Go to ...
2. Click on ...
3. Scroll down to ...

# Expected Behavior

To work as expected.

# Screenshots
If applicable, add screenshots to help explain the problem.

# Additional Context

```php
Warning: fopen(/var/www/html/cpdemo/wp-content/plugins/codepotent-head-cleaner/codepotent-head-cleaner.php): failed to open stream: No such file or directory in /var/www/html/cpdemo/wp-includes/functions.php on line 4903
Warning: fread() expects parameter 1 to be resource, bool given in /var/www/html/cpdemo/wp-includes/functions.php on line 4906
Warning: fclose() expects parameter 1 to be resource, bool given in /var/www/html/cpdemo/wp-includes/functions.php on line 4909
Warning: require_once(/var/www/html/cpdemo/wp-content/plugins/codepotent-head-cleaner/classes/UpdateClient.class.php): failed to open stream: No such file or directory in /var/www/html/cpdemo/wp-content/plugins/Head-Cleaner-1.0.0/codepotent-head-cleaner.php on line 71
Fatal error: require_once(): Failed opening required '/var/www/html/cpdemo/wp-content/plugins/codepotent-head-cleaner/classes/UpdateClient.class.php' (include_path='.:/usr/share/php') in /var/www/html/cpdemo/wp-content/plugins/Head-Cleaner-1.0.0/codepotent-head-cleaner.php on line 71
```

# Environment
> Under which type of environment did you experience this problem?

Local ClassicPress demo website.

**Desktop**
 - Operating System: GNU / Linux Debian testing 64-bit
 - Browser & Version: Firefox 78.3.0esr (64-bit)

**Comment by johnalarcon** [comment]
As noted in the repo's readme:

> _Branch downloads and clones are for development; not for general use._

Install a release version.

**Comment by stefanos82** [comment]
Oops, I thought I downloaded the right one.

I went here https://github.com/codepotent/Head-Cleaner/tags and downloaded the .zip format; I did not get inside `1.0.0.` to download the actual plugin.

**Comment by johnalarcon** [comment]
No worries. My onsite plugin directory is probably the easiest place to find links to all the working production versions. 👍 

https://codepotent.com/classicpress/plugins/

**Comment by stefanos82** [comment]
codepotent.com: bookmarked! :1st_place_medal:
